### ISSUE TITLE
Entering Time on time tracking

### ISSUE THREAD

**Issue by HMStitt** [argosity/stockor#12]
When you are picking a project, if you type in the project field, you have to type first letter twice in order to get where you want to go...first time just opens the list box. I think if you type in P for instance then it should open box with only ones with P showing.

**Comment by nathanstitt** [comment]
This is a common problem with the select boxes but is going to be difficult to fix.  The issue is that the first keypress causes the box to open, but it has no records loaded for the selection.  This causes the first keypress to not match any records so it has no effect.  Then when the records complete loading the second keypress will match and select them.

Ideally we'll have to modify the select box to remember the first keypress and then attempt a match once the results are available.
