### ISSUE TITLE
Time Entry Suggestion

### ISSUE THREAD

**Issue by HMStitt** [argosity/stockor#19]
I think the save and cancel button should be reversed.  As I tab through I think I would be hitting save more than cancel therefor less tabs to get to it...just a thought

**Comment by nathanstitt** [comment]
I think it's important that the primary (save) button be on the right.  That's pretty much the standard UI pattern.   However, I've changed the form to no longer tab to the cancel button and to save when enter is pressed on any of the fields. 

I also changed the form to start editing on the hours field since that's the flow that I easiest.
